other:
  url: jdbc:jtds:sybase://1.1.1.1:5000/FL_HIS;charset=cp936
server:
  port: 8080
spring:
  application:
    name: springboot-sybase
  datasource:
    driver-class-name: net.sourceforge.jtds.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: ${other.url}
    username: mz_interface
    password: mz_interface
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
