server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-oauth2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: admin
      password: 123456
      roles: [read, write]
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6380
    database: 5
    password: 123456
logging:
  level:
    org.springframework.security: DEBUG
